Updated functions
mrc-ide/first90release pull request #8
Opened 2019-01-29 17:34 UTC by m-maheu-giroux

Hi alex,

I corrected the errors (I think). Could you check that everything runs smoothly.

Best,
mathieu

2019-01-30 10:12 UTC, hillalex requested changes
Thanks for this! I refactored slightly to make more amenable to testing, and added some tests here:
https://github.com/mrc-ide/first90release/pull/9

Most tests are passing, but still a couple of edge cases failing. 
In particular I think the ones to look at are:
`combine_rows treats inconsistent rows as NA`
`combine_rows merges duplicate rows`

If those are fixed then the failing smoke tests will also pass.

2019-01-30 10:13 UTC, littledice commented
Oh I did also create another branch yesterday with my own fix, but I think actually the plotting logic is slightly different, so feel free to just ignore it, but if of interest it's here: https://github.com/mrc-ide/first90release/pull/7

2019-01-30 21:40 UTC, littledice commented
Ok, as pointed out in https://github.com/mrc-ide/first90release/pull/9 data validation should be handled prior to passing data to the plotting functions, so this is looking good. I suggest we merge https://github.com/mrc-ide/first90release/pull/9 to add the tests, and then merge this branch to master.

2019-02-04 10:48 UTC, hillalex approved these changes

2019-02-04 11:18 UTC, merged